### ISSUE TITLE
[update] board 1개 가져오기 기능에 추천 게시물 추가하기

### ISSUE THREAD

**Issue by ombuu** [h-dt/hola-clone#41]
##  board 1개 가져오기 기능에 추천 게시물 추가하기
board 1개 가져올때 우측에 있는 추천 게시물 리스트를 추가하고자 합니다. 

### 추가/개선 필요 요소
1. boardDetailDto에 게시물 추천 리스트 추가
2. 추천게시글 로직 회의하기

### 스크린샷
 
![image](https://user-images.githubusercontent.com/77061427/175660589-3849c6ac-c6e7-424e-aa97-be32459d2bbb.png)

**Comment by dnwlsrla40** [comment]
추천 게시글은 단순히 조회수로만 하기보단 score(점수)라는 column을 만들고 점수는 조회수 + 최신 등록글 + 댓글 수 등을 조합해서 점수 매기는 로직을 만드는 경우가 많아요 요즘은 AI 딥러닝 등을 쓰기도 한다고 들었던 거 같은데 우선 저흰 저희만의 로직을 만들어 봐요 의논해서!

**Comment by ombuu** [comment]
넵 알겠습니다!

**Comment by jiji-hoon96** [comment]
추천 게시글은 프로젝트 or 스터디 구분없이 조회수 순서대로 기록되나요?

**Comment by ombuu** [comment]
hola 사이트에서는 프로젝트/스터디 구분없이 추천해주는거 같아서 동일하게 진행하려고 합니다.  추천 순위도 우진님이 말씀해 주신것처럼 조회수, 댓글수, 최신등록일을 점수로 합산해서 만들고 있습니다!

**Comment by jiji-hoon96** [comment]
그럼 백앤드에서 합산값이 넘어와서 저는 출력한것 띄우면 된다 => 라고 이해하면 될까요!?

**Comment by ombuu** [comment]
네네! 합산값의 상위 10개 title을 List에 넣어서 보내고 싶은데,  List<String> 형태로 보내도 될까요?

**Comment by jiji-hoon96** [comment]
java에서 List <String> 형태가 어떤걸 의미하는지 잘몰르겠습니다
혹시 postman에 api 로 기록되어있나요?

**Comment by ombuu** [comment]
아니요 지금 만들다 막혀서 헤매고 있어서요ㅠ skills 보내는 형식과 동일하게 보내려고 합니다.

**Comment by dnwlsrla40** [comment]
제가 react를 정확히 몰라서 그러는데 skill_type(String 형의 기술 이름)의 배열형으로 보내면 nav바에서 해당 게시글 클릭시 id로 호출이 가능한가요? 만약 아니라면 title로 게시글 검색 로직을 추가 작성하거나 List<String>형이 아닌 List<Board>등으로 보내서 id와 title정보를 같이 보내줘야 할 것 같습니다.

**Comment by jiji-hoon96** [comment]
만약 게시글의 url을 설정할때 id값으로 해놓으면 가능합니다! 
Ex) localhost3000/project/(id값) 이면 각 게시글 클릭하면 이동가능합니다다아마 project 와 study의 id 값이 달라지면 좋겟지만요! 
게시글의 id를 순서대로 하실건지 아니면 url 에서도 사용할 수있도록 랜덤한 16자리 아이디값을 사용하는지도 생각해봐야될거같습니다!
Id,title 두개 보내주셔도 문제는 없을 거같습니다
